# Generated by Django 5.0.2 on 2025-10-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0004_materia_maestros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='materias',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='creation',
        ),
        migrations.AddField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
