# Generated by Django 5.0.2 on 2025-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0005_remove_maestros_materias_remove_maestros_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
