# Generated by Django 5.0.2 on 2025-11-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0006_alumnos_ocupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestros',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
